import { EventRegistrationRecord } from './events.types'

export const initialEventRegistrations: EventRegistrationRecord[] = [
    {
        id: 'registration-evt-1',
        campaign_id: 'campaign-1',
        module_id: 'module-event-1',
        student: {
            id: 'student-1',
            full_name: 'Nguyen Van An',
            student_code: '21110001',
            email: '21110001@student.dut.udn.vn',
        },
        status: 'COMPLETED',
        answers: {
            faculty: 'Khoa Cong nghe Thong tin',
            skills: ['So hoa tai lieu', 'Huong dan nguoi dan'],
            note: 'San sang ho tro ca ngay cuoi tuan.',
        },
        registered_at: '2026-06-16T08:00:00.000Z',
        reviewed_at: '2026-06-16T10:00:00.000Z',
        review_note: 'Da bo tri vao doi hinh tai xa.',
        checked_in_at: '2026-07-15T07:30:00.000Z',
        checked_out_at: '2026-07-15T17:30:00.000Z',
        hours: 8,
    },
    {
        id: 'registration-evt-2',
        campaign_id: 'campaign-2',
        module_id: 'module-event-2',
        student: {
            id: 'student-2',
            full_name: 'Le Thi Binh',
            student_code: '21110002',
            email: '21110002@student.dut.udn.vn',
        },
        status: 'APPROVED',
        answers: {
            faculty: 'Khoa Co khi',
            skills: ['Dieu phoi', 'Lam viec nhom'],
            note: 'Co the truc som tai diem thi.',
        },
        registered_at: '2026-06-22T08:00:00.000Z',
        reviewed_at: '2026-06-22T11:00:00.000Z',
        review_note: 'Phu hop nhom dieu phoi thi sinh.',
        checked_in_at: null,
        checked_out_at: null,
        hours: null,
    },
    {
        id: 'registration-evt-3',
        campaign_id: 'campaign-3',
        module_id: 'module-event-3',
        student: {
            id: 'student-3',
            full_name: 'Pham Quoc Cuong',
            student_code: '21110003',
            email: '21110003@student.dut.udn.vn',
        },
        status: 'PENDING',
        answers: {
            faculty: 'Khoa Dien',
            skills: ['To chuc su kien', 'MC'],
            note: 'Mong muon tham gia ngay hoi trao hoc bong.',
        },
        registered_at: '2026-06-04T08:30:00.000Z',
        reviewed_at: null,
        review_note: null,
        checked_in_at: null,
        checked_out_at: null,
        hours: null,
    },
    {
        id: 'registration-evt-4',
        campaign_id: 'campaign-3',
        module_id: 'module-event-3',
        student: {
            id: 'student-4',
            full_name: 'Tran Minh Chau',
            student_code: '21110004',
            email: '21110004@student.dut.udn.vn',
        },
        status: 'APPROVED',
        answers: {
            faculty: 'Khoa Xay dung',
            skills: ['Hau can', 'Truyen thong'],
            note: 'Co the phu trach tiep don hoc sinh.',
        },
        registered_at: '2026-06-04T09:00:00.000Z',
        reviewed_at: '2026-06-04T11:00:00.000Z',
        review_note: 'Bo tri nhom tiep tan va dieu phoi.',
        checked_in_at: null,
        checked_out_at: null,
        hours: null,
    },
]
