export { default as adminRouter } from './admin/admin.route'
export { default as approvalsRouter } from './approvals/approvals.route'
export { default as authRouter } from './auth/auth.route'
export { default as campaignsRouter } from './campaigns/campaigns.route'
export { default as certificatesRouter } from './certificates/certificates.route'
export { default as eventsRouter } from './events/events.route'
export { default as fundraisingRouter } from './fundraising/fundraising.route'
export { default as itemDonationsRouter } from './item-donations/item-donations.route'
export { default as notificationsRouter } from './notifications/notifications.route'
export { default as organizationsRouter } from './organizations/organizations.route'
export { default as publicRouter } from './public/public.route'
export { default as reportsRouter } from './reports/reports.route'
export { default as studentsRouter } from './students/students.route'

