-- Contract database baseline
--
-- Source of truth: prisma/schema.prisma and docs/02_thiet_ke_database_mysql.md.
-- Executable migration SQL is generated in:
-- prisma/migrations/20260505000000_contract_schema/migration.sql
