import {
    CampaignCertificateRecord,
    CertificateTemplateRecord,
} from './certificates.types'

const certificateDataUrl = (code: string) =>
    `data:text/plain;charset=utf-8,Certificate%20${encodeURIComponent(code)}%20-%20BKVolunteers`

export const initialCertificateTemplates: CertificateTemplateRecord[] = [
    {
        id: 'tpl-1',
        name: 'Mau hoan thanh chien dich',
        type: 'VOLUNTEER',
        file_url: null,
        layout_json: {
            version: 1,
            fields: ['student_name', 'campaign_title', 'issued_at'],
        },
        status: 'ACTIVE',
        is_locked: true,
        created_by: 'board-user',
        created_at: '2026-05-20T08:00:00.000Z',
        updated_at: '2026-06-01T08:00:00.000Z',
    },
    {
        id: 'tpl-2',
        name: 'Mau dong gop va gay quy',
        type: 'DONOR',
        file_url: null,
        layout_json: {
            version: 1,
            fields: ['student_name', 'campaign_title', 'module_title'],
        },
        status: 'ACTIVE',
        is_locked: false,
        created_by: 'board-user',
        created_at: '2026-05-28T08:00:00.000Z',
        updated_at: '2026-06-02T08:00:00.000Z',
    },
]

export const initialCampaignCertificates: CampaignCertificateRecord[] = [
    {
        id: 'cert-1',
        certificate_no: 'CERT-2026-001',
        campaign_id: 'campaign-1',
        module_id: 'module-event-1',
        module_title: 'Doi hinh so hoa tai lieu',
        student_id: 'student-1',
        student_name: 'Nguyen Van An',
        student_code: '21110001',
        template_id: 'tpl-1',
        template_name: 'Mau hoan thanh chien dich',
        status: 'SIGNED',
        snapshot_json: {
            campaign_title: 'Mua He Xanh So Hoa 2026',
        },
        file_url: certificateDataUrl('CERT-2026-001'),
        file_hash: 'hash-cert-1',
        issued_at: '2026-07-25T08:30:00.000Z',
        revoked_at: null,
        revoked_by: null,
        revoke_reason: null,
        replacement_certificate_id: null,
        created_at: '2026-07-25T08:30:00.000Z',
        updated_at: '2026-07-25T08:30:00.000Z',
    },
    {
        id: 'cert-2',
        certificate_no: 'CERT-2026-002',
        campaign_id: 'campaign-1',
        module_id: 'module-fundraising-1',
        module_title: 'Quy hoc bong thiet bi hoc tap',
        student_id: 'student-2',
        student_name: 'Le Thi Binh',
        student_code: '21110002',
        template_id: 'tpl-2',
        template_name: 'Mau dong gop va gay quy',
        status: 'READY',
        snapshot_json: {
            campaign_title: 'Mua He Xanh So Hoa 2026',
        },
        file_url: certificateDataUrl('CERT-2026-002'),
        file_hash: 'hash-cert-2',
        issued_at: '2026-07-26T08:30:00.000Z',
        revoked_at: null,
        revoked_by: null,
        revoke_reason: null,
        replacement_certificate_id: null,
        created_at: '2026-07-26T08:30:00.000Z',
        updated_at: '2026-07-26T08:30:00.000Z',
    },
    {
        id: 'cert-3',
        certificate_no: 'CERT-2026-003',
        campaign_id: 'campaign-2',
        module_id: 'module-event-2',
        module_title: 'Truc diem thi va ho tro thi sinh',
        student_id: 'student-3',
        student_name: 'Pham Quoc Cuong',
        student_code: '21110003',
        template_id: 'tpl-1',
        template_name: 'Mau hoan thanh chien dich',
        status: 'REVOKED',
        snapshot_json: {
            campaign_title: 'Tiep Suc Mua Thi 2026',
        },
        file_url: certificateDataUrl('CERT-2026-003'),
        file_hash: 'hash-cert-3',
        issued_at: '2026-07-12T08:00:00.000Z',
        revoked_at: '2026-07-20T08:00:00.000Z',
        revoked_by: 'board-user',
        revoke_reason: 'Cap nhat sai gio cong',
        replacement_certificate_id: null,
        created_at: '2026-07-12T08:00:00.000Z',
        updated_at: '2026-07-20T08:00:00.000Z',
    },
]
